### ISSUE TITLE
Contribuidor, Rezende viado

### ISSUE THREAD

**Issue by DevNatan** [Hyrran/CreeperCSS#1]
Olha oque eu to fazendo pra você gostoso,
me da permissão pra contribuir:

default:
http://prntscr.com/hf9vio
http://prntscr.com/hf9vmo
http://prntscr.com/hf9vpy

black (classes .inverse):
http://prntscr.com/hf9vx4
http://prntscr.com/hf9vzs
http://prntscr.com/hf9w2k
http://prntscr.com/hf9w73

**Comment by Hyrran** [comment]
Manda a pull request ai
